Added support of css styles
pixijs/html-text pull request #14
Opened 2022-03-31 04:41 UTC by ChasLui

```js
      const text = '<p>Lorem <a href="#">ipsum</a> dolor sit amet, &#x1F680; <b>consectetur adipiscing elit</b>.</p> <p>Phasellus porta nisi est, vitae <i>sagittis ex gravida ac</i>. Sed vitae malesuada neque.</p>';
      const cssStyle = {
        '&': 'position: relative; line-height: 48px; height: 96px; overflow: hidden;',
        // Multi-line text overflow ellipsis through pseudo-elements
        '&::after': 'content: "..."; position: absolute; bottom: 0;right: 0; background: #999999;',
        'p': 'margin-bottom: 0;margin-top: 30px;',
        'p:nth-of-type(1)': 'margin: 0;',
        'a': 'color: aquamarine;'
      }

      const text2 = new PIXI.HTMLText(text, style, null, cssStyle);
```

![image](https://user-images.githubusercontent.com/10083758/160977957-273621ba-3c1f-4907-9245-e47a6aefb193.png)

2022-03-31 12:11 UTC, bigtimebuddy commented
I like this addition, thanks @ChasLui

2022-03-31 17:28 UTC, bigtimebuddy commented on src/index.js
> +            for (const key in cssObject) {
```suggestion
            for (const key in cssObject)
            {
```

2022-03-31 17:28 UTC, bigtimebuddy commented on src/index.js
> +                if (cssObject.hasOwnProperty(key)) {
```suggestion
                if (cssObject.hasOwnProperty(key))
                {
```

2022-03-31 17:29 UTC, bigtimebuddy commented on src/index.js
> +            if (/^&/.test(selector)) selector = selector.replace('&', '');
```suggestion
            if ((/^&/).test(selector)) selector = selector.replace('&', '');
```

2022-03-31 17:30 UTC, bigtimebuddy commented on src/index.js
> +     * @member {string}
```suggestion
     * @member {object}
```

2022-04-18 03:04 UTC, ChasLui commented
merge origin main, please review @bigtimebuddy

2022-05-06 09:22 UTC, bigtimebuddy commented
I'm not seeing any changes after you forced push.

2022-05-18 12:17 UTC, bigtimebuddy requested changes
Overall, I like this idea. Very useful and powerful, but I think there are a few things that can be improved:

## Feedback

### constructor args

The arguments are getting unwieldy here (text, style, canvas, cssStyle). Whenever you have to set null a parameter just to set another parameter, things get kinda messy. My suggestion it to do (text, style, options) or (text, style, canvas). This keeps it consistent with Text, but also allows us to add more options in the future (which I'm thinking about for custom fonts and other ideas).

### cssStyle and dirty

One of the features of TextStyle is that when a user modifies a property then the style  triggers a dirty on the Text or Texts elements. But if you change the CSS style object here, it doesn't set the HTMLText element to dirty. That feels a little inconsistent.

### Convention

You're introducing a convention `&` which is a Sass/Less construct which maps to the internal root name. This is not a CSS language feature and while it makes things more readable and can confuse users too. Why not just use `root` as the class name and set this as the convention `.root::after`, etc. It's not _that_ more verbose, easier to document, valid CSS, and less "magical". 

## Suggestions

* Add options as a third argument to the constructor to support cssStyle
* Is there a way to use CSSStyleSheet in the browser for setting the rules/styles? There's already an API that's well supported in all browsers for organizing this information.
* If CSSStyleSheet doesn't make sense, consider removing the css object -> string translation all together. Just have `cssStyle` be a string that the user provides and be done with it. I think this is actually more powerful because a user can load a stylesheet outside of this flow:

```js
const cssStyle = await fetch('./text.css').then(res => res.text());
const text = new HTMLText('Hello World', {}, { cssStyle });
```
* Lastly, consider using `root` instead of `pixi-html_text` and removing the `&` convenience setter. It's not valid CSS (therefore hard to lint/validate) and potentially confusing.

2022-12-01 20:27 UTC, bigtimebuddy commented
I'm going to close this PR. I think adding more styles has value, but this PR isn't the right approach for the reasons above. @ChasLui if you want to keep working on this, I'm happy to re-open.

2022-12-01 20:27 UTC, closed without merging